application:
  name: umami
  project: umami
  publicly_accessible: true
  organization: QoveryCommunity
databases:
- type: postgresql
  version: "12"
  name: my-postgresql
routers:
- name: main
  routes:
  - application_name: umami
    paths:
    - /
